// Generated by `bun init`

declare module '*.svg' {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`
  export = path
}

declare module '*.png' {
  /**
   * A path to the png file
   */
  const path: `${string}.png`
  export = path
}

declare module '*.webp' {
  /**
   * A path to the webp file
   */
  const path: `${string}.webp`
  export = path
}

declare module '*.module.css' {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: {readonly [key: string]: string}
  export = classes
}
